/*
 * Copyright (c) 2015 Magnet Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * File generated by Magnet Magnet Lang Tool on May 26, 2015 4:44:56 PM
 * @see {@link http://developer.magnet.com}
 */
package com.magnet.max.android.tests.testsubjects;

import retrofit.MagnetCall;
import retrofit.http.*;

public interface DateType {

  /**
   * 
   * POST date-type/date
   * @param input style:Header optional:false
   * @param callback asynchronous callback
   */
  @POST("date-type/date") MagnetCall<java.util.Date> postDate(
     @Header("input") java.util.Date input,
     retrofit.Callback<java.util.Date> callback
  );

  /**
   * 
   * PUT date-type/date
   * @param input style:Header optional:false
   * @param callback asynchronous callback
   */
  @PUT("date-type/date")
  MagnetCall<java.util.Date> putDate(
     @Header("input") java.util.Date input,
     retrofit.Callback<java.util.Date> callback
  );

  /**
   * 
   * GET date-type/date
   * @param input style:Header optional:false
   * @param callback asynchronous callback
   */
  @GET("date-type/date")
  MagnetCall<java.util.Date> getDate(
     @Header("input") java.util.Date input,
     retrofit.Callback<java.util.Date> callback
  );

  /**
   * 
   * DELETE date-type/date
   * @param input style:Header optional:false
   * @param callback asynchronous callback
   */
  @HTTP(method = "DELETE", path = "date-type/date", hasBody = true)
  MagnetCall<java.util.Date> deleteDate(
     @Header("input") java.util.Date input,
     retrofit.Callback<java.util.Date> callback
  );

  /**
   * 
   * POST date-type/jsondate
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("date-type/jsondate")
  MagnetCall<java.util.Date> postJsonDate(
     @Body java.util.Date body,
     retrofit.Callback<java.util.Date> callback
  );

}
