/*
 * Copyright (c) 2015 Magnet Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * File generated by Magnet Magnet Lang Tool on Apr 20, 2015 1:44:51 PM
 * @see {@link http://developer.magnet.com}
 */
package com.magnet.max.android.tests.testsubjects;

import com.magnet.max.android.tests.testsubjects.model.EnumAttribute;
import com.magnet.max.android.tests.testsubjects.model.ModelWithAllTypes;

import java.util.Map;
import retrofit.MagnetCall;
import retrofit.http.*;

public interface PrimitiveTypeService {

  /**
   *
   * POST primitive-type-service/returnMapOfIntegers
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnMapOfIntegers")
  MagnetCall<Map<String, Integer>> returnMapOfIntegers(
          @Body java.util.Map<String, Integer> body,
          retrofit.Callback<java.util.Map<String, Integer>> callback
  );

  /**
   *
   * POST primitive-type-service/returnMapOfCharacters
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnMapOfCharacters")
  MagnetCall<java.util.Map<String, Character>> returnMapOfCharacters(
          @Body java.util.Map<String, Character> body,
          retrofit.Callback<java.util.Map<String, Character>> callback
  );

  /**
   *
   * POST primitive-type-service/returnListOfBooleans
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnListOfBooleans")
  MagnetCall<java.util.List<Boolean>> returnListOfBooleans(
          @Body java.util.List<Boolean> body,
          retrofit.Callback<java.util.List<Boolean>> callback
  );

  /**
   *
   * POST primitive-type-service/returnMapOfBytes
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnMapOfBytes")
  MagnetCall<java.util.Map<String, Byte>> returnMapOfBytes(
          @Body java.util.Map<String, Byte> body,
          retrofit.Callback<java.util.Map<String, Byte>> callback
  );

  /**
   *
   * POST primitive-type-service/returnShort
   * @param input style:Field optional:false
   * @param callback asynchronous callback
   */
  @FormUrlEncoded
  @POST("primitive-type-service/returnShort")
  MagnetCall<Short> returnShortWithFormParameters(
          @Field("input") Short input,
          retrofit.Callback<Short> callback
  );

  /**
   *
   * PUT primitive-type-service/returnShort
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @PUT("primitive-type-service/returnShort")
  MagnetCall<Short> returnShortWithBodyParameters(
          @Body Short body,
          retrofit.Callback<Short> callback
  );

  /**
   *
   * GET primitive-type-service/returnShort
   * @param input style:Query optional:false
   * @param callback asynchronous callback
   */
  @GET("primitive-type-service/returnShort")
  MagnetCall<Short> returnShort(
          @Query("input") Short input,
          retrofit.Callback<Short> callback
  );

  /**
   *
   * POST primitive-type-service/returnMapOfLongs
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnMapOfLongs")
  MagnetCall<java.util.Map<String, Long>> returnMapOfLongs(
          @Body java.util.Map<String, Long> body,
          retrofit.Callback<java.util.Map<String, Long>> callback
  );

  /**
   *
   * POST primitive-type-service/returnListOfBytes
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnListOfBytes")
  MagnetCall<java.util.List<Byte>> returnListOfBytes(
          @Body java.util.List<Byte> body,
          retrofit.Callback<java.util.List<Byte>> callback
  );

  /**
   *
   * POST primitive-type-service/returnListOfCharacters
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnListOfCharacters")
  MagnetCall<java.util.List<Character>> returnListOfCharacters(
          @Body java.util.List<Character> body,
          retrofit.Callback<java.util.List<Character>> callback
  );

  /**
   *
   * POST primitive-type-service/returnListOfLongs
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnListOfLongs")
  MagnetCall<java.util.List<Long>> returnListOfLongs(
          @Body java.util.List<Long> body,
          retrofit.Callback<java.util.List<Long>> callback
  );

  /**
   *
   * POST primitive-type-service/returnDouble
   * @param input style:Field optional:false
   * @param callback asynchronous callback
   */
  @FormUrlEncoded
  @POST("primitive-type-service/returnDouble")
  MagnetCall<Double> returnDoubleWithFormParameters(
          @Field("input") Double input,
          retrofit.Callback<Double> callback
  );

  /**
   *
   * PUT primitive-type-service/returnDouble
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @PUT("primitive-type-service/returnDouble")
  MagnetCall<Double> returnDoubleWithBodyParameters(
          @Body Double body,
          retrofit.Callback<Double> callback
  );

  /**
   *
   * GET primitive-type-service/returnDouble
   * @param input style:Query optional:false
   * @param callback asynchronous callback
   */
  @GET("primitive-type-service/returnDouble")
  MagnetCall<Double> returnDouble(
          @Query("input") Double input,
          retrofit.Callback<Double> callback
  );

  /**
   *
   * POST primitive-type-service/returnInt
   * @param input style:Field optional:false
   * @param callback asynchronous callback
   */
  @FormUrlEncoded
  @POST("primitive-type-service/returnInt")
  MagnetCall<Integer> returnIntWithFormParameters(
          @Field("input") Integer input,
          retrofit.Callback<Integer> callback
  );

  /**
   *
   * PUT primitive-type-service/returnInt
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @PUT("primitive-type-service/returnInt")
  MagnetCall<Integer> returnIntWithBodyParameters(
          @Body Integer body,
          retrofit.Callback<Integer> callback
  );

  /**
   *
   * GET primitive-type-service/returnInt
   * @param input style:Query optional:false
   * @param callback asynchronous callback
   */
  @GET("primitive-type-service/returnInt")
  MagnetCall<Integer> returnInt(
          @Query("input") Integer input,
          retrofit.Callback<Integer> callback
  );

  /**
   *
   * POST primitive-type-service/returnString
   * @param input style:Field optional:false
   * @param callback asynchronous callback
   */
  @FormUrlEncoded
  @POST("primitive-type-service/returnString")
  MagnetCall<String> returnStringWithFormParameters(
          @Field("input") String input,
          retrofit.Callback<String> callback
  );

  /**
   *
   * PUT primitive-type-service/returnString
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @PUT("primitive-type-service/returnString")
  MagnetCall<String> returnStringWithBodyParameters(
          @Body String body,
          retrofit.Callback<String> callback
  );

  /**
   *
   * GET primitive-type-service/returnString
   * @param input style:Query optional:false
   * @param callback asynchronous callback
   */
  @GET("primitive-type-service/returnString")
  MagnetCall<String> returnString(
          @Query("input") String input,
          retrofit.Callback<String> callback
  );

  /**
   *
   * POST primitive-type-service/returnMapOfShorts
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnMapOfShorts")
  MagnetCall<java.util.Map<String, Short>> returnMapOfShorts(
          @Body java.util.Map<String, Short> body,
          retrofit.Callback<java.util.Map<String, Short>> callback
  );

  /**
   *
   * POST primitive-type-service/returnMapOfBooleans
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnMapOfBooleans")
  MagnetCall<java.util.Map<String, Boolean>> returnMapOfBooleans(
          @Body java.util.Map<String, Boolean> body,
          retrofit.Callback<java.util.Map<String, Boolean>> callback
  );

  /**
   *
   * POST primitive-type-service/returnListOfIntegers
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnListOfIntegers")
  MagnetCall<java.util.List<Integer>> returnListOfIntegers(
          @Body java.util.List<Integer> body,
          retrofit.Callback<java.util.List<Integer>> callback
  );

  /**
   *
   * POST primitive-type-service/returnListOfEnums
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnListOfEnums")
  MagnetCall<java.util.List<EnumAttribute>> returnListOfEnums(
          @Body java.util.List<EnumAttribute> body,
          retrofit.Callback<java.util.List<EnumAttribute>> callback
  );

  /**
   *
   * POST primitive-type-service/returnByte
   * @param input style:Field optional:false
   * @param callback asynchronous callback
   */
  @FormUrlEncoded
  @POST("primitive-type-service/returnByte")
  MagnetCall<Byte> returnByteWithFormParameters(
          @Field("input") Byte input,
          retrofit.Callback<Byte> callback
  );

  /**
   *
   * PUT primitive-type-service/returnByte
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @PUT("primitive-type-service/returnByte")
  MagnetCall<Byte> returnByteWithBodyParameters(
          @Body Byte body,
          retrofit.Callback<Byte> callback
  );

  /**
   *
   * GET primitive-type-service/returnByte
   * @param input style:Query optional:false
   * @param callback asynchronous callback
   */
  @GET("primitive-type-service/returnByte")
  MagnetCall<Byte> returnByte(
          @Query("input") Byte input,
          retrofit.Callback<Byte> callback
  );

  /**
   *
   * POST primitive-type-service/returnEnum
   * @param input style:Field optional:false
   * @param callback asynchronous callback
   */
  @FormUrlEncoded
  @POST("primitive-type-service/returnEnum")
  MagnetCall<EnumAttribute> returnEnumWithFormParameters(
          @Field("input") EnumAttribute input,
          retrofit.Callback<EnumAttribute> callback
  );

  /**
   *
   * PUT primitive-type-service/returnEnum
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @PUT("primitive-type-service/returnEnum")
  MagnetCall<EnumAttribute> returnEnumWithBodyParameters(
          @Body EnumAttribute body,
          retrofit.Callback<EnumAttribute> callback
  );

  /**
   *
   * GET primitive-type-service/returnEnum
   * @param input style:Query optional:false
   * @param callback asynchronous callback
   */
  @GET("primitive-type-service/returnEnum")
  MagnetCall<EnumAttribute> returnEnum(
          @Query("input") EnumAttribute input,
          retrofit.Callback<EnumAttribute> callback
  );

  /**
   *
   * POST primitive-type-service/returnMapOfDoubles
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnMapOfDoubles")
  MagnetCall<java.util.Map<String, Double>> returnMapOfDoubles(
          @Body java.util.Map<String, Double> body,
          retrofit.Callback<java.util.Map<String, Double>> callback
  );

  /**
   *
   * POST primitive-type-service/returnListOfDoubles
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnListOfDoubles")
  MagnetCall<java.util.List<Double>> returnListOfDoubles(
          @Body java.util.List<Double> body,
          retrofit.Callback<java.util.List<Double>> callback
  );

  /**
   *
   * POST primitive-type-service/returnMapOfModels
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnMapOfModels")
  MagnetCall<java.util.Map<String, ModelWithAllTypes>> returnMapOfModels(
          @Body java.util.Map<String, ModelWithAllTypes> body,
          retrofit.Callback<java.util.Map<String, ModelWithAllTypes>> callback
  );

  /**
   *
   * GET primitive-type-service/returnVoid
   * @param callback asynchronous callback
   */
  @GET("primitive-type-service/returnVoid")
  MagnetCall<Void> returnVoid(
          retrofit.Callback<Void> callback
  );

  /**
   *
   * POST primitive-type-service/returnListOfFloats
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnListOfFloats")
  MagnetCall<java.util.List<Float>> returnListOfFloats(
          @Body java.util.List<Float> body,
          retrofit.Callback<java.util.List<Float>> callback
  );

  /**
   *
   * POST primitive-type-service/returnBoolean
   * @param input style:Field optional:false
   * @param callback asynchronous callback
   */
  @FormUrlEncoded
  @POST("primitive-type-service/returnBoolean")
  MagnetCall<Boolean> returnBooleanWithFormParameters(
          @Field("input") Boolean input,
          retrofit.Callback<Boolean> callback
  );

  /**
   *
   * PUT primitive-type-service/returnBoolean
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @PUT("primitive-type-service/returnBoolean")
  MagnetCall<Boolean> returnBooleanWithBodyParameters(
          @Body Boolean body,
          retrofit.Callback<Boolean> callback
  );

  /**
   *
   * GET primitive-type-service/returnBoolean
   * @param input style:Query optional:false
   * @param callback asynchronous callback
   */
  @GET("primitive-type-service/returnBoolean")
  MagnetCall<Boolean> returnBoolean(
          @Query("input") Boolean input,
          retrofit.Callback<Boolean> callback
  );

  /**
   *
   * POST primitive-type-service/returnListOfModels
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnListOfModels")
  MagnetCall<java.util.List<ModelWithAllTypes>> returnListOfModels(
          @Body java.util.List<ModelWithAllTypes> body,
          retrofit.Callback<java.util.List<ModelWithAllTypes>> callback
  );

  /**
   *
   * POST primitive-type-service/returnMapOfEnums
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnMapOfEnums")
  MagnetCall<java.util.Map<String, EnumAttribute>> returnMapOfEnums(
          @Body java.util.Map<String, EnumAttribute> body,
          retrofit.Callback<java.util.Map<String, EnumAttribute>> callback
  );

  /**
   *
   * POST primitive-type-service/returnFloat
   * @param input style:Field optional:false
   * @param callback asynchronous callback
   */
  @FormUrlEncoded
  @POST("primitive-type-service/returnFloat")
  MagnetCall<Float> returnFloatWithFormParameters(
          @Field("input") Float input,
          retrofit.Callback<Float> callback
  );

  /**
   *
   * PUT primitive-type-service/returnFloat
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @PUT("primitive-type-service/returnFloat")
  MagnetCall<Float> returnFloatWithBodyParameters(
          @Body Float body,
          retrofit.Callback<Float> callback
  );

  /**
   *
   * GET primitive-type-service/returnFloat
   * @param input style:Query optional:false
   * @param callback asynchronous callback
   */
  @GET("primitive-type-service/returnFloat")
  MagnetCall<Float> returnFloat(
          @Query("input") Float input,
          retrofit.Callback<Float> callback
  );

  /**
   *
   * POST primitive-type-service/returnMapOfStrings
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnMapOfStrings")
  MagnetCall<java.util.Map<String, String>> returnMapOfStrings(
          @Body java.util.Map<String, String> body,
          retrofit.Callback<java.util.Map<String, String>> callback
  );

  /**
   *
   * POST primitive-type-service/returnModelWithAllTypes
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnModelWithAllTypes")
  MagnetCall<ModelWithAllTypes> returnModelWithAllTypes(
          @Body ModelWithAllTypes body,
          retrofit.Callback<ModelWithAllTypes> callback
  );

  /**
   *
   * POST primitive-type-service/returnMapOfFloats
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnMapOfFloats")
  MagnetCall<java.util.Map<String, Float>> returnMapOfFloats(
          @Body java.util.Map<String, Float> body,
          retrofit.Callback<java.util.Map<String, Float>> callback
  );

  /**
   *
   * POST primitive-type-service/returnChar
   * @param input style:Field optional:false
   * @param callback asynchronous callback
   */
  @FormUrlEncoded
  @POST("primitive-type-service/returnChar")
  MagnetCall<Character> returnCharWithFormParameters(
          @Field("input") Character input,
          retrofit.Callback<Character> callback
  );

  /**
   *
   * PUT primitive-type-service/returnChar
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @PUT("primitive-type-service/returnChar")
  MagnetCall<Character> returnCharWithBodyParameters(
          @Body Character body,
          retrofit.Callback<Character> callback
  );

  /**
   *
   * GET primitive-type-service/returnChar
   * @param input style:Query optional:false
   * @param callback asynchronous callback
   */
  @GET("primitive-type-service/returnChar")
  MagnetCall<Character> returnChar(
          @Query("input") Character input,
          retrofit.Callback<Character> callback
  );

  /**
   *
   * POST primitive-type-service/returnListOfStrings
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnListOfStrings")
  MagnetCall<java.util.List<String>> returnListOfStrings(
          @Body java.util.List<String> body,
          retrofit.Callback<java.util.List<String>> callback
  );

  /**
   *
   * POST primitive-type-service/returnListOfShorts
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("primitive-type-service/returnListOfShorts")
  MagnetCall<java.util.List<Short>> returnListOfShorts(
          @Body java.util.List<Short> body,
          retrofit.Callback<java.util.List<Short>> callback
  );

  /**
   *
   * POST primitive-type-service/returnLong
   * @param input style:Field optional:false
   * @param callback asynchronous callback
   */
  @FormUrlEncoded
  @POST("primitive-type-service/returnLong")
  MagnetCall<Long> returnLongWithFormParameters(
          @Field("input") Long input,
          retrofit.Callback<Long> callback
  );

  /**
   *
   * PUT primitive-type-service/returnLong
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @PUT("primitive-type-service/returnLong")
  MagnetCall<Long> returnLongWithBodyParameters(
          @Body Long body,
          retrofit.Callback<Long> callback
  );

  /**
   *
   * GET primitive-type-service/returnLong
   * @param input style:Query optional:false
   * @param callback asynchronous callback
   */
  @GET("primitive-type-service/returnLong")
  MagnetCall<Long> returnLong(
          @Query("input") Long input,
          retrofit.Callback<Long> callback
  );

}