/*
 * Copyright (c) 2015 Magnet Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * File generated by Magnet Magnet Lang Tool on Apr 20, 2015 11:05:23 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.max.android.tests.testsubjects.model;

import org.apache.commons.lang3.ObjectUtils;

public class SubModel {

  
  
  private Integer intAttribute;

  
  private String stringAttribute;

  public Integer getIntAttribute() {
    return intAttribute;
  }

  public String getStringAttribute() {
    return stringAttribute;
  }

  @Override
  public boolean equals(Object object) {
    if(null == object) {
      return false;
    }

    SubModel theOther = (SubModel) object;
    return ObjectUtils.equals(intAttribute, theOther.getIntAttribute()) && ObjectUtils.equals(stringAttribute, theOther.getStringAttribute());
  }

  /**
  * Builder for SubModel
  **/
  public static class SubModelBuilder {
    private SubModel toBuild = new SubModel();

    public SubModelBuilder() {
    }

    public SubModel build() {
      return toBuild;
    }

    public SubModelBuilder intAttribute(Integer value) {
      toBuild.intAttribute = value;
      return this;
    }

    public SubModelBuilder stringAttribute(String value) {
      toBuild.stringAttribute = value;
      return this;
    }
  }
}
