/*
 * Copyright (c) 2015 Magnet Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * File generated by Magnet Magnet Lang Tool on Jun 16, 2015 10:53:46 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.max.android.auth.model;

public class AuthToken {

  private Boolean anonymous;

  private Long tokenExpiresIn;

  
  private Boolean authenticated;

  
  private Long tokenCreationTime;

  
  private String[] roles;

  
  private String userId;

  
  private String userName;

  
  private String clientId;

  
  private String deviceId;

  public Boolean getAnonymous() {
    return anonymous;
  }

  public Long getTokenExpiresIn() {
    return tokenExpiresIn;
  }

  public Boolean getAuthenticated() {
    return authenticated;
  }

  public Long getTokenCreationTime() {
    return tokenCreationTime;
  }

  public String[] getRoles() {
    return roles;
  }

  public String getUserId() {
    return userId;
  }

  public String getUserName() {
    return userName;
  }

  public String getClientId() {
    return clientId;
  }

  public String getDeviceId() {
    return deviceId;
  }


  /**
  * Builder for AuthToken
  **/
  public static class AuthTokenBuilder {
    private final AuthToken toBuild = new AuthToken();

    public AuthTokenBuilder() {
    }

    public AuthToken build() {
      return toBuild;
    }

    public AuthTokenBuilder anonymous(Boolean value) {
      toBuild.anonymous = value;
      return this;
    }

    public AuthTokenBuilder tokenExpiresIn(Long value) {
      toBuild.tokenExpiresIn = value;
      return this;
    }

    public AuthTokenBuilder authenticated(Boolean value) {
      toBuild.authenticated = value;
      return this;
    }

    public AuthTokenBuilder tokenCreationTime(Long value) {
      toBuild.tokenCreationTime = value;
      return this;
    }

    public AuthTokenBuilder roles(String[] value) {
      toBuild.roles = value;
      return this;
    }

    public AuthTokenBuilder userId(String value) {
      toBuild.userId = value;
      return this;
    }

    public AuthTokenBuilder userName(String value) {
      toBuild.userName = value;
      return this;
    }

    public AuthTokenBuilder clientId(String value) {
      toBuild.clientId = value;
      return this;
    }

    public AuthTokenBuilder deviceId(String value) {
      toBuild.deviceId = value;
      return this;
    }
  }
}
