/*
 * Copyright (c) 2015 Magnet Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * File generated by Magnet Magnet Lang Tool on Jun 16, 2015 10:53:46 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.max.android.auth.model;

public class ClientRegistrationRequest {

  
  
  private String tag;

  
  private String client_description;

  
  private String client_name;

  
  private String password;

  public String getTag() {
    return tag;
  }

  public String getClient_description() {
    return client_description;
  }

  public String getClient_name() {
    return client_name;
  }

  public String getPassword() {
    return password;
  }


  /**
  * Builder for ClientRegistrationRequest
  **/
  public static class ClientRegistrationRequestBuilder {
    private ClientRegistrationRequest toBuild = new ClientRegistrationRequest();

    public ClientRegistrationRequestBuilder() {
    }

    public ClientRegistrationRequest build() {
      return toBuild;
    }

    public ClientRegistrationRequestBuilder tag(String value) {
      toBuild.tag = value;
      return this;
    }

    public ClientRegistrationRequestBuilder client_description(String value) {
      toBuild.client_description = value;
      return this;
    }

    public ClientRegistrationRequestBuilder client_name(String value) {
      toBuild.client_name = value;
      return this;
    }

    public ClientRegistrationRequestBuilder password(String value) {
      toBuild.password = value;
      return this;
    }
  }
}
