/*
 * Copyright (c) 2015 Magnet Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * File generated by Magnet Magnet Lang Tool on Jun 16, 2015 10:53:46 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.max.android.auth.model;

public class Client {

  
  
  private String internalId;

  
  private String clientDescription;

  
  private String oauthSecret;

  
  private TimeUnit expirationTimeUnit;

  
  private java.util.Date createdTime;

  
  private UserStatus clientStatus;

  
  private Long expiresIn;

  
  private String clientName;

  
  private String redirectUrl;

  
  private String oauthClientId;

  public String getInternalId() {
    return internalId;
  }

  public String getClientDescription() {
    return clientDescription;
  }

  public String getOauthSecret() {
    return oauthSecret;
  }

  public TimeUnit getExpirationTimeUnit() {
    return expirationTimeUnit;
  }

  public java.util.Date getCreatedTime() {
    return createdTime;
  }

  public UserStatus getClientStatus() {
    return clientStatus;
  }

  public Long getExpiresIn() {
    return expiresIn;
  }

  public String getClientName() {
    return clientName;
  }

  public String getRedirectUrl() {
    return redirectUrl;
  }

  public String getOauthClientId() {
    return oauthClientId;
  }


  /**
  * Builder for Client
  **/
  public static class ClientBuilder {
    private Client toBuild = new Client();

    public ClientBuilder() {
    }

    public Client build() {
      return toBuild;
    }

    public ClientBuilder internalId(String value) {
      toBuild.internalId = value;
      return this;
    }

    public ClientBuilder clientDescription(String value) {
      toBuild.clientDescription = value;
      return this;
    }

    public ClientBuilder oauthSecret(String value) {
      toBuild.oauthSecret = value;
      return this;
    }

    public ClientBuilder expirationTimeUnit(TimeUnit value) {
      toBuild.expirationTimeUnit = value;
      return this;
    }

    public ClientBuilder createdTime(java.util.Date value) {
      toBuild.createdTime = value;
      return this;
    }

    public ClientBuilder clientStatus(UserStatus value) {
      toBuild.clientStatus = value;
      return this;
    }

    public ClientBuilder expiresIn(Long value) {
      toBuild.expiresIn = value;
      return this;
    }

    public ClientBuilder clientName(String value) {
      toBuild.clientName = value;
      return this;
    }

    public ClientBuilder redirectUrl(String value) {
      toBuild.redirectUrl = value;
      return this;
    }

    public ClientBuilder oauthClientId(String value) {
      toBuild.oauthClientId = value;
      return this;
    }
  }
}
