/*
 * Copyright (c) 2015 Magnet Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * File generated by Magnet Magnet Lang Tool on Jun 16, 2015 10:53:46 AM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.max.android.auth.model;

import android.os.Parcel;
import android.os.Parcelable;
import com.google.gson.annotations.SerializedName;

public class UserToken implements Parcelable {

  @SerializedName("expires_in")
  private Long expiresIn;

  @SerializedName("access_token")
  private String accessToken;

  @SerializedName("token_type")
  private String tokenType;

  private Long creationTime;

  public UserToken(Long expiresIn, String accessToken, String tokenType) {
    this.expiresIn = expiresIn;
    this.accessToken = accessToken;
    this.tokenType = tokenType;
  }

  public Long getExpiresIn() {
    return expiresIn;
  }

  public void setExpiresIn(Long expiresIn) {
    this.expiresIn = expiresIn;
  }

  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  public String getTokenType() {
    return tokenType;
  }

  public void setTokenType(String tokenType) {
    this.tokenType = tokenType;
  }

  public Long getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(Long creationTime) {
    this.creationTime = creationTime;
  }

  @Override public int describeContents() {
    return 0;
  }

  @Override public void writeToParcel(Parcel dest, int flags) {
    dest.writeValue(this.expiresIn);
    dest.writeString(this.accessToken);
    dest.writeString(this.tokenType);
    dest.writeValue(this.creationTime);
  }

  public UserToken() {
  }

  protected UserToken(Parcel in) {
    this.expiresIn = (Long) in.readValue(Long.class.getClassLoader());
    this.accessToken = in.readString();
    this.tokenType = in.readString();
    this.creationTime = (Long) in.readValue(Long.class.getClassLoader());
  }

  public static final Parcelable.Creator<UserToken> CREATOR = new Parcelable.Creator<UserToken>() {
    public UserToken createFromParcel(Parcel source) {
      return new UserToken(source);
    }

    public UserToken[] newArray(int size) {
      return new UserToken[size];
    }
  };
}
