/*
 * Copyright (c) 2015 Magnet Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * File generated by Magnet Magnet Lang Tool on Jun 16, 2015 10:53:47 AM
 * @see {@link http://developer.magnet.com}
 */
package com.magnet.max.android.auth;

import com.magnet.max.android.auth.model.MMRole;
import retrofit.http.*;

public interface RolesService {

  /**
   * 
   * GET /api/roles/{roleName}
   * @param roleName style:Path optional:false
   * @param callback asynchronous callback
   */
  @GET("/api/com.magnet.server/roles/{roleName}")
  void getRole(
     @Path("roleName") String roleName,
     retrofit.Callback<MMRole> callback
  );

  /**
   * 
   * DELETE /api/roles/{roleName}
   * @param roleName style:Path optional:false
   * @param callback asynchronous callback
   */
  @HTTP(method = "DELETE", path = "/api/com.magnet.server/roles/{roleName}", hasBody = true)
  void deleteRole(
     @Path("roleName") String roleName,
     retrofit.Callback<Boolean> callback
  );

  /**
   * 
   * GET /api/roles
   * @param callback asynchronous callback
   */
  @GET("/api/com.magnet.server/roles")
  void getRoles(
     retrofit.Callback<java.util.List<MMRole>> callback
  );

  /**
   * 
   * PUT /api/roles/{roleId}
   * @param roleId style:Path optional:false
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @PUT("/api/com.magnet.server/roles/{roleId}")
  void updateRole(
     @Path("roleId") String roleId,
     @Body MMRole body,
     retrofit.Callback<MMRole> callback
  );

  /**
   * 
   * POST /api/roles/role
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("/api/com.magnet.server/roles/role")
  void addRole(
     @Body MMRole body,
     retrofit.Callback<MMRole> callback
  );

}
