/*
 * Copyright (c) 2015 Magnet Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * File generated by Magnet Magnet Lang Tool on Jul 9, 2015 1:41:58 PM
 * @see {@link http://developer.magnet.com}
 */
package com.magnet.max.android.logging.remote;

import com.magnet.max.android.logging.EventLog;
import retrofit.MagnetCall;
import retrofit.http.*;

public interface LogEventsCollectionService {

  /**
   * 
   * POST /api/collections/batch
   * @param file style:Query optional:false
   * @param callback asynchronous callback
   */
  @Multipart
  @POST("/api/com.magnet.server/collections/events/batch")
  MagnetCall<Void> addEventsFromFile(@Part("file") com.squareup.okhttp.RequestBody file, retrofit.Callback<Void> callback);

  /**
   * 
   * POST /api/collections/events
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @POST("/api/com.magnet.server/collections/events")
  MagnetCall<Boolean> addEvents(@Body java.util.List<EventLog> body, retrofit.Callback<Boolean> callback);

}
